version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: us-east-1
    ACCOUNT_ID: 905418049972

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version

      # Login to ECR
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

      # Repositories
      - SPRING_REPO=$ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/springboot-app
      - FILEBEAT_REPO=$ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/filebeat-sidecar

      # Tag
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')

  build:
    commands:
      - echo Build started on `date`

      #################################
      # Build Spring Boot
      #################################
      - echo Building Spring Boot JAR...
      - mvn clean install

      - echo Building Spring Boot Docker image...
      - docker build -t $SPRING_REPO:latest .
      - docker tag $SPRING_REPO:latest $SPRING_REPO:$IMAGE_TAG

      #################################
      # Build Filebeat Sidecar
      #################################
      - echo Building Filebeat image...
      - docker build -t $FILEBEAT_REPO:latest ./filebeat
      - docker tag $FILEBEAT_REPO:latest $FILEBEAT_REPO:$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed on `date`

      #################################
      # Push Spring Boot
      #################################
      - echo Pushing Spring Boot image...
      - docker push $SPRING_REPO:latest
      - docker push $SPRING_REPO:$IMAGE_TAG

      #################################
      # Push Filebeat
      #################################
      - echo Pushing Filebeat image...
      - docker push $FILEBEAT_REPO:latest
      - docker push $FILEBEAT_REPO:$IMAGE_TAG

      #################################
      # ECS Deployment file (ONLY APP)
      #################################
      - echo Writing imagedefinitions.json...
      - DOCKER_CONTAINER_NAME=springboot-app
      - printf '[{"name":"%s","imageUri":"%s"}]' $DOCKER_CONTAINER_NAME $SPRING_REPO:$IMAGE_TAG > imagedefinitions.json

      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
